# Generated by Django 3.2.4 on 2021-06-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CusContract',
            fields=[
                ('cnt_id', models.DecimalField(decimal_places=0, max_digits=13, primary_key=True, serialize=False)),
                ('cus_id', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('cus_brn', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('cus_vol', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'Test',
                'managed': False,
            },
        ),
    ]
