# Generated by Django 3.2.4 on 2021-06-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cuscontract_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CusContract',
            new_name='Test',
        ),
    ]
