# Generated by Django 3.2.4 on 2021-06-07 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_cuscontract_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
