# Generated by Django 3.2.4 on 2021-06-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timescan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitecode', models.CharField(max_length=15)),
                ('date_scan', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('sh_code', models.CharField(blank=True, max_length=5, null=True)),
                ('sh_name', models.CharField(blank=True, max_length=50, null=True)),
                ('d_code', models.CharField(blank=True, max_length=50, null=True)),
                ('user_code', models.CharField(blank=True, max_length=10, null=True)),
                ('sitename', models.CharField(blank=True, max_length=100, null=True)),
                ('date_save', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('date_process', models.DateTimeField(blank=True, null=True)),
                ('op1', models.CharField(blank=True, max_length=1, null=True)),
                ('op2', models.CharField(blank=True, max_length=1, null=True)),
                ('op3', models.CharField(blank=True, max_length=1, null=True)),
                ('op4', models.CharField(blank=True, max_length=1, null=True)),
                ('op5', models.CharField(blank=True, max_length=1, null=True)),
                ('upd_date', models.DateTimeField(blank=True, db_column='UPD_date', null=True)),
                ('upd_by', models.CharField(blank=True, db_column='UPD_by', max_length=25, null=True)),
                ('upd_flag', models.CharField(blank=True, db_column='UPD_flag', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Timescan',
                'managed': True,
            },
        ),
    ]
