# Generated by Django 3.2.4 on 2021-06-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_timescan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timescan',
            old_name='sitecode',
            new_name='site_code',
        ),
    ]
