# Generated by Django 3.2.4 on 2021-06-07 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_sitecode_timescan_site_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timescan',
            table='timescan',
        ),
    ]
