# Generated by Django 3.2.4 on 2021-06-07 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_timescan_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timescan',
        ),
    ]
