# Generated by Django 3.2.4 on 2021-06-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_timescan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timescan',
            old_name='sitename',
            new_name='site_name',
        ),
    ]
